import { env } from 'cloudflare:workers';
const statements=[
`CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL,created_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS couple_spaces (id TEXT PRIMARY KEY,name TEXT NOT NULL,created_by TEXT NOT NULL,created_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS memberships (id TEXT PRIMARY KEY,space_id TEXT NOT NULL,user_id TEXT NOT NULL,role TEXT NOT NULL,joined_at TEXT NOT NULL,UNIQUE(space_id,user_id))`,
`CREATE TABLE IF NOT EXISTS invites (id TEXT PRIMARY KEY,space_id TEXT NOT NULL,code TEXT NOT NULL UNIQUE,token TEXT NOT NULL UNIQUE,created_by TEXT NOT NULL,expires_at TEXT NOT NULL,used_at TEXT,used_by TEXT)`,
`CREATE TABLE IF NOT EXISTS moments (id TEXT PRIMARY KEY,space_id TEXT NOT NULL,author_id TEXT NOT NULL,kind TEXT NOT NULL,title TEXT NOT NULL,note TEXT NOT NULL,happened_at TEXT NOT NULL,created_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS media_assets (id TEXT PRIMARY KEY,space_id TEXT NOT NULL,moment_id TEXT,owner_id TEXT NOT NULL,object_key TEXT NOT NULL,content_type TEXT NOT NULL,created_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS future_letters (id TEXT PRIMARY KEY,space_id TEXT NOT NULL,author_id TEXT NOT NULL,body TEXT NOT NULL,opens_at TEXT NOT NULL,created_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS ritual_responses (id TEXT PRIMARY KEY,space_id TEXT NOT NULL,ritual_key TEXT NOT NULL,user_id TEXT NOT NULL,answer TEXT NOT NULL,completed_at TEXT NOT NULL,UNIQUE(space_id,ritual_key,user_id))`,
`CREATE TABLE IF NOT EXISTS activity_sessions (id TEXT PRIMARY KEY,space_id TEXT NOT NULL,activity_key TEXT NOT NULL,room_code TEXT NOT NULL UNIQUE,status TEXT NOT NULL,state_json TEXT NOT NULL,started_at TEXT NOT NULL,finished_at TEXT)`,
`CREATE TABLE IF NOT EXISTS activity_events (id TEXT PRIMARY KEY,session_id TEXT NOT NULL,user_id TEXT NOT NULL,event_type TEXT NOT NULL,payload_json TEXT NOT NULL,sequence INTEGER NOT NULL,created_at TEXT NOT NULL,UNIQUE(session_id,sequence))`,
`CREATE INDEX IF NOT EXISTS idx_moments_space_date ON moments(space_id,happened_at)`,`CREATE INDEX IF NOT EXISTS idx_memberships_user ON memberships(user_id)`,`CREATE INDEX IF NOT EXISTS idx_activity_space ON activity_sessions(space_id)`];
export async function db(){const database=env.DB as D1Database;await database.batch(statements.map(statement=>database.prepare(statement)));return database}
export async function spaceForUser(userId:string){const database=await db();return database.prepare('SELECT space_id AS spaceId FROM memberships WHERE user_id = ? LIMIT 1').bind(userId).first<{spaceId:string}>()}
export async function ensureSpaceForUser(user:{userId:string;email:string;displayName:string}){const existing=await spaceForUser(user.userId);if(existing)return existing;const database=await db(),now=new Date().toISOString(),spaceId=crypto.randomUUID();await database.batch([database.prepare('INSERT OR IGNORE INTO users (id,email,display_name,created_at) VALUES (?,?,?,?)').bind(user.userId,user.email,user.displayName,now),database.prepare('INSERT INTO couple_spaces (id,name,created_by,created_at) VALUES (?,?,?,?)').bind(spaceId,'Our Space',user.userId,now),database.prepare('INSERT INTO memberships (id,space_id,user_id,role,joined_at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),spaceId,user.userId,'owner',now)]);return{spaceId}}
